### ISSUE TITLE
Incompatibility with Server_Devcommands?

### ISSUE THREAD

**Issue by xXRhaenyraXx** [nbusseneau/BetterCartographyTable#12]
Hi!

I run a NoMap server with this fantastic mod - however, this mod seems to override Server_Devcommands capability to re-enable the map again for admins. Is there a solution for this? I have attempted to add mod onto greylist so admin can disable it, however, it is checking with the server and preventing this from being a simple solution.

Thanks !

**Comment by nbusseneau** [comment]
Hey, thanks for the report. This should be fixed by e8a170f759de0ee8a8732101b9d8f2bf2f397f84, released in [0.5.10](https://github.com/nbusseneau/BetterCartographyTable/releases/tag/0.5.10).

**Comment by xXRhaenyraXx** [comment]
Nope, not fixed lol

**Comment by nbusseneau** [comment]
I can't reproduce this anymore with latest version, can you give your reproduction steps? A minimal isolated setup would be even better.

**Comment by xXRhaenyraXx** [comment]
Fixed now as of nbusseneau-Better_Cartography_Table-0.5.12 ! Thank you !!!

**Comment by nbusseneau** [comment]
OK I guess there was just confusion and admins did not update to 0.5.10 or above (.11 and .12 are not changing anything w.r.t. to that one ^^).

**Comment by xXRhaenyraXx** [comment]
It was initially installed 0.5.10, updated to 0.5.11, and todays update 0.5.12 has fixed it on both server and offline oddly enough :)

**Comment by nbusseneau** [comment]
Well, still, there were absolutely 0 changes for that in .11 and .12 though :D Anyway, glad it's fixed.
