### ISSUE TITLE
Unintended interaction between BetterCartographyTable by nbusseneau and Ressurection By Smoothbrain

### ISSUE THREAD

**Issue by cCaptainn** [nbusseneau/BetterCartographyTable#14]
Description:

While using BCT and Resurrection By Smoothbrain, dying when you would generate a tombstone (ie with items in your inventory) toggles "Visible to Other Players" option ON on the map. Dying with items in your inventory when that effect is toggled ON for any reason, either after it toggles itself on or after you manually toggle it on, then generates a Player icon on the map (the same on you would see if a player toggled "Visible to Other Players") that cannot be manually deleted. That icon will vanish after logging out. 

To Reproduce

• Install Resurrection 1.0.11.
• Install BetterCartographyTable 0.5.12.
• Launch game.
• Interact with a Cartography Table and ensure you have "Visible to Other Players" toggled off.
• Put items into inventory.
• Die.
• Go back to Cartography Table and verify that "Visible to Other Players" is now toggled on.
• Leaving it toggled on, interact with your Tombstone to regain your items.
• Die again.
• Check map for new Player pin that cannot be deleted until relogging.

Related Links: 
https://github.com/blaxxun-boop/Resurrection
https://github.com/nbusseneau/BetterCartographyTable

Related Issue: https://github.com/blaxxun-boop/Resurrection/issues/8

Notes: If you need any additional input from me let me know.

**Comment by nbusseneau** [comment]
Hey, thanks for the report. Is there any error or warning in the log from either mod?

**Comment by cCaptainn** [comment]
None at all. It actually took me a few hours to track down the conflict because of that. Here's a log either way.
[LogOutput.log](https://github.com/user-attachments/files/16501595/LogOutput.log)

**Comment by nbusseneau** [comment]
I'm confused since I see you have just closed the issue, was this fixed? I haven't had a chance to look at it yet.
