### ISSUE TITLE
Public pins get wiped if the Cartography Table is in use while a world save occurs

### ISSUE THREAD

**Issue by GPlayah** [nbusseneau/BetterCartographyTable#2]
Hey man. Me and a friend experienced a rather inconvenient issue.
We both had the cartography map open (I was the host, listen server), messing with pins and figuring out how the mod worked, and I saw the usual world autosave message appear in the upper corner. In the same instant, all the green Public pins vanished, for both me and my friend, and were not recoverable.
I was able to replicate this myself later. If the Cartography Table map is open, and a save occurs, all Public pins get wiped.
Let me know if I can give any more info.

**Comment by nbusseneau** [comment]
Hey, thanks for the report. This is indeed a bug, will think on how to address it :)

**Comment by nbusseneau** [comment]
This should be fixed by 31ff57cebe77a3b26b510cba30c8e0ee1f3f9ab5, released in [0.2.0](https://github.com/nbusseneau/BetterCartographyTable/releases/tag/0.2.0).
