### ISSUE TITLE
Game crashing error

### ISSUE THREAD

**Issue by Fudgedup** [nbusseneau/BetterCartographyTable#3]
I attached a screenshot of the error. Ive been playing for about 15 hours or so with a bunch of mods. no issues until I went on a long exploration and when I came back to my base the Error just continually happens. It also rolled back my server like 15 mins or so. It might be from a custom pin? I use a mod called REBUILT_AMPED_AutoMapPainsEnhanced. it has custom pins for stuff like berries and mushrooms. I attached a screenshot of the pins for reference.

![Better Cartography Error](https://github.com/nbusseneau/BetterCartographyTable/assets/98511748/2c26e426-7efe-4606-83f9-773f852908e9)

![image](https://github.com/nbusseneau/BetterCartographyTable/assets/98511748/aa3d93ab-44c3-461e-b61a-e642bdb5af65)

**Comment by nbusseneau** [comment]
Thanks for the report :)
Yes it looks like there's an incompatibility with that mod since it adds pins that are not expected by mine. I will try to reproduce and think on how / if to fix.

**Comment by nbusseneau** [comment]
Yeah so that mod is definitely not compatible as is. I didn't manage to reproduce the crash but in any case the mod does its own click handling on top of the auto-pinning mechanism, and thus both mods are interfering with each other anyhow. We are both trying to replace the vanilla mechanism with our own, hence the incompatibility.

I have to think some more, I probably can do some things to improve compatibility on my side, though it will definitely still not ensure compatibility with all other pin mods.

**Comment by Fudgedup** [comment]
Thanks so much! would love to use your mod in conjunction with the auto-marker. Ill keep an eye out for updates. The crash only happened when I tried to exit the game after being spammed with the error. it didnt just close the game instantly. I tried to log out and the game just closed

**Comment by nbusseneau** [comment]
Yeah so I looked a bit more in depth, and in this specific case it will not be fixable without changes being also made to the other mod: Harmony explicitly warns against multiple mods using prefixes and skipping the original method for this reason. Glancing at the code over at https://github.com/raziell74/Valheim-AMPED-Auto-Map-Pins-Enhanced it seems AMP intercepts clicks to implement its own closest pin detection mechanism, with a shorter radius than in vanilla, and also removing pin ownership edition (which I'm actually unsure is intended, considering the git log).

While I still intend to make some changes on my side to improve potential compatibility with other mods, this specific incompatibility with AMP will not be solved :/

What can be done:
- Use the other popular auto-marker mod https://valheim.thunderstore.io/package/FixItFelix/AutoMapPins/ which does not intercept map clicks and is thus compatible.
- Get in touch with AMP's author and ask if they're willing to collaborate on addressing this. Issue is I'm not quite sure who should be contacted. @raziell74 seems to have done the latest changes a year ago published at https://valheim.thunderstore.io/package/raziell74/AMPED_Auto_Map_Pins_Enhanced/, but @Galll1 is the one that rebuilt AMP for the latest version of Valheim published at https://valheim.thunderstore.io/package/Pineapple/REBUILT_AMPED_AutoMapPinsEnhanced/... So what's the actual situation? 😅 Is any one of you two actively maintaining the mod?

**Comment by nbusseneau** [comment]
This should be greatly improved in version [0.4.0](https://github.com/nbusseneau/BetterCartographyTable/releases/tag/0.4.0).
