### ISSUE TITLE
Add No Map Functionality 

### ISSUE THREAD

**Issue by Atlasroar** [nbusseneau/BetterCartographyTable#5]
Add a toggle for the ability to view the map when using the read function on no map servers.

**Comment by Atlasroar** [comment]
TLDR: this https://thunderstore.io/c/valheim/p/Visteus/NoMap_Cartography_Map/

**Comment by nbusseneau** [comment]
Implemented in 0000ca4aa2472277789da1b3758d6b0eddc9222f, released in [0.3.0](https://github.com/nbusseneau/BetterCartographyTable/releases/tag/0.3.0).
