### ISSUE TITLE
Getting Crashes, Loss of mobility etc with this mod and another. [bug]

### ISSUE THREAD

**Issue by Atlasroar** [nbusseneau/BetterCartographyTable#7]
----- 716x -----
[Error  : Unity Log] InvalidCastException: Specified cast is not valid.
Stack trace:
(wrapper castclass) System.Object.__castclass_with_cache(object,intptr,intptr)
System.Linq.Enumerable+<CastIterator>d__34`1[TResult].MoveNext () (at <a790f10e63dd4341b206460141e07e75>:0)
System.Linq.Enumerable+WhereEnumerableIterator`1[TSource].MoveNext () (at <a790f10e63dd4341b206460141e07e75>:0)
BetterCartographyTable.UI.MinimapManagerUI.UpdatePins () (at <30c2a97e47dc4320b532fd7ef8e77b59>:0)
BetterCartographyTable.UI.MinimapManagerUI.OnUpdatePins () (at <30c2a97e47dc4320b532fd7ef8e77b59>:0)
BetterCartographyTable.Patches.MinimapPatches+UpdateUIOnUpdatePins.Postfix () (at <30c2a97e47dc4320b532fd7ef8e77b59>:0)
(wrapper dynamic-method) Minimap.DMD<Minimap::UpdatePins>(Minimap)
(wrapper dynamic-method) Minimap.DMD<Minimap::Update>(Minimap)
----------------

[Warning: Unity Log] 04/05/2024 15:02:00: Missing item prefab GreatbowModer_TW
[Warning: Unity Log] 04/05/2024 15:02:00: Missing item prefab KnifeWrench_TW

----- 40x -----
[Error  : Unity Log] InvalidCastException: Specified cast is not valid.
Stack trace:
(wrapper castclass) System.Object.__castclass_with_cache(object,intptr,intptr)
System.Linq.Enumerable+<CastIterator>d__34`1[TResult].MoveNext () (at <a790f10e63dd4341b206460141e07e75>:0)
System.Linq.Enumerable+WhereEnumerableIterator`1[TSource].MoveNext () (at <a790f10e63dd4341b206460141e07e75>:0)
BetterCartographyTable.UI.MinimapManagerUI.UpdatePins () (at <30c2a97e47dc4320b532fd7ef8e77b59>:0)
BetterCartographyTable.UI.MinimapManagerUI.OnUpdatePins () (at <30c2a97e47dc4320b532fd7ef8e77b59>:0)
BetterCartographyTable.Patches.MinimapPatches+UpdateUIOnUpdatePins.Postfix () (at <30c2a97e47dc4320b532fd7ef8e77b59>:0)
(wrapper dynamic-method) Minimap.DMD<Minimap::UpdatePins>(Minimap)
(wrapper dynamic-method) Minimap.DMD<Minimap::Update>(Minimap)
---------------

[Error  : Unity Log] InvalidCastException: Specified cast is not valid.
Stack trace:
(wrapper castclass) System.Object.__castclass_with_cache(object,intptr,intptr)
System.Linq.Enumerable+<CastIterator>d__34`1[TResult].MoveNext () (at <a790f10e63dd4341b206460141e07e75>:0)
System.Linq.Enumerable+WhereEnumerableIterator`1[TSource].ToList () (at <a790f10e63dd4341b206460141e07e75>:0)
System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <a790f10e63dd4341b206460141e07e75>:0)
BetterCartographyTable.Managers.MinimapManager.RemovePins (System.Collections.Generic.IEnumerable`1[T] pins) (at <30c2a97e47dc4320b532fd7ef8e77b59>:0)
BetterCartographyTable.Managers.MinimapManager.ReplaceMinimapPinsWithTablePins (MapTable mapTable) (at <30c2a97e47dc4320b532fd7ef8e77b59>:0)
BetterCartographyTable.Managers.InteractionManager.OnMapTableUse (MapTable mapTable, Humanoid user) (at <30c2a97e47dc4320b532fd7ef8e77b59>:0)
BetterCartographyTable.Patches.MapTablePatches+StartInteractionOnMapTableUse.Prefix (MapTable __instance, Switch caller, Humanoid user, ItemDrop+ItemData item, System.Boolean& __result) (at <30c2a97e47dc4320b532fd7ef8e77b59>:0)
(wrapper dynamic-method) MapTable.DMD<MapTable::OnRead>(MapTable,Switch,Humanoid,ItemDrop/ItemData)
(wrapper dynamic-method) Switch.DMD<Switch::Interact>(Switch,Humanoid,bool,bool)
(wrapper dynamic-method) Player.DMD<Player::Interact>(Player,UnityEngine.GameObject,bool,bool)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

----- 128x -----
[Error  : Unity Log] InvalidCastException: Specified cast is not valid.
Stack trace:
(wrapper castclass) System.Object.__castclass_with_cache(object,intptr,intptr)
System.Linq.Enumerable+<CastIterator>d__34`1[TResult].MoveNext () (at <a790f10e63dd4341b206460141e07e75>:0)
System.Linq.Enumerable+WhereEnumerableIterator`1[TSource].MoveNext () (at <a790f10e63dd4341b206460141e07e75>:0)
System.Collections.Generic.List`1[T].AddEnumerable (System.Collections.Generic.IEnumerable`1[T] enumerable) (at <834b2ded5dad441e8c7a4287897d63c7>:0)
System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) (at <834b2ded5dad441e8c7a4287897d63c7>:0)
System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <a790f10e63dd4341b206460141e07e75>:0)
BetterCartographyTable.Patches.MinimapPatches+InjectPublicPinsInGetSharedMapData.Prefix () (at <30c2a97e47dc4320b532fd7ef8e77b59>:0)
(wrapper dynamic-method) Minimap.DMD<Minimap::GetSharedMapData>(Minimap,byte[])
MapTable.GetMapData (System.Byte[] currentMapData) (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
BetterCartographyTable.Extensions.MapTableExtensions.StoreExploredMapAndPublicPinsInZDO (MapTable mapTable) (at <30c2a97e47dc4320b532fd7ef8e77b59>:0)
BetterCartographyTable.Extensions.MapTableExtensions.SyncVanillaSharedData (MapTable mapTable) (at <30c2a97e47dc4320b532fd7ef8e77b59>:0)
BetterCartographyTable.Managers.InteractionManager.OnMapClose () (at <30c2a97e47dc4320b532fd7ef8e77b59>:0)
BetterCartographyTable.Patches.MinimapPatches+HandleInteractionsOnMapModeChange.Postfix (Minimap+MapMode mode) (at <30c2a97e47dc4320b532fd7ef8e77b59>:0)
(wrapper dynamic-method) Minimap.DMD<Minimap::SetMapMode>(Minimap,Minimap/MapMode)
(wrapper dynamic-method) Minimap.DMD<Minimap::Update>(Minimap)
----------------

----- 405x -----
[Error  : Unity Log] InvalidCastException: Specified cast is not valid.
Stack trace:
(wrapper castclass) System.Object.__castclass_with_cache(object,intptr,intptr)
System.Linq.Enumerable+<CastIterator>d__34`1[TResult].MoveNext () (at <a790f10e63dd4341b206460141e07e75>:0)
System.Linq.Enumerable+WhereEnumerableIterator`1[TSource].MoveNext () (at <a790f10e63dd4341b206460141e07e75>:0)
BetterCartographyTable.UI.MinimapManagerUI.UpdatePins () (at <30c2a97e47dc4320b532fd7ef8e77b59>:0)
BetterCartographyTable.UI.MinimapManagerUI.OnUpdatePins () (at <30c2a97e47dc4320b532fd7ef8e77b59>:0)
BetterCartographyTable.Patches.MinimapPatches+UpdateUIOnUpdatePins.Postfix () (at <30c2a97e47dc4320b532fd7ef8e77b59>:0)
(wrapper dynamic-method) Minimap.DMD<Minimap::UpdatePins>(Minimap)
(wrapper dynamic-method) Minimap.DMD<Minimap::Update>(Minimap)
----------------

----- 1960x -----
[Error  : Unity Log] InvalidCastException: Specified cast is not valid.
Stack trace:
(wrapper castclass) System.Object.__castclass_with_cache(object,intptr,intptr)
System.Linq.Enumerable+<CastIterator>d__34`1[TResult].MoveNext () (at <a790f10e63dd4341b206460141e07e75>:0)
System.Linq.Enumerable+WhereEnumerableIterator`1[TSource].MoveNext () (at <a790f10e63dd4341b206460141e07e75>:0)
System.Collections.Generic.List`1[T].AddEnumerable (System.Collections.Generic.IEnumerable`1[T] enumerable) (at <834b2ded5dad441e8c7a4287897d63c7>:0)
System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) (at <834b2ded5dad441e8c7a4287897d63c7>:0)
System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <a790f10e63dd4341b206460141e07e75>:0)
BetterCartographyTable.Patches.MinimapPatches+InjectPublicPinsInGetSharedMapData.Prefix () (at <30c2a97e47dc4320b532fd7ef8e77b59>:0)
(wrapper dynamic-method) Minimap.DMD<Minimap::GetSharedMapData>(Minimap,byte[])
MapTable.GetMapData (System.Byte[] currentMapData) (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
BetterCartographyTable.Extensions.MapTableExtensions.StoreExploredMapAndPublicPinsInZDO (MapTable mapTable) (at <30c2a97e47dc4320b532fd7ef8e77b59>:0)
BetterCartographyTable.Extensions.MapTableExtensions.SyncVanillaSharedData (MapTable mapTable) (at <30c2a97e47dc4320b532fd7ef8e77b59>:0)
BetterCartographyTable.Managers.InteractionManager.OnMapClose () (at <30c2a97e47dc4320b532fd7ef8e77b59>:0)
BetterCartographyTable.Patches.MinimapPatches+HandleInteractionsOnMapModeChange.Postfix (Minimap+MapMode mode) (at <30c2a97e47dc4320b532fd7ef8e77b59>:0)
(wrapper dynamic-method) Minimap.DMD<Minimap::SetMapMode>(Minimap,Minimap/MapMode)
(wrapper dynamic-method) Minimap.DMD<Minimap::Update>(Minimap)
-----------------

[Error  : Unity Log] InvalidCastException: Specified cast is not valid.
Stack trace:
(wrapper castclass) System.Object.__castclass_with_cache(object,intptr,intptr)
System.Linq.Enumerable+<CastIterator>d__34`1[TResult].MoveNext () (at <a790f10e63dd4341b206460141e07e75>:0)
System.Linq.Enumerable+WhereEnumerableIterator`1[TSource].GetCount (System.Boolean onlyIfCheap) (at <a790f10e63dd4341b206460141e07e75>:0)
System.Linq.Enumerable.Count[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <a790f10e63dd4341b206460141e07e75>:0)
BetterCartographyTable.Model.IEnumerableSharablePinDataExtensions.ToZPackage (System.Collections.Generic.IEnumerable`1[T] pins) (at <30c2a97e47dc4320b532fd7ef8e77b59>:0)
BetterCartographyTable.Managers.PlayerSaveManager.StorePinsInPlayerSavefile (System.Collections.Generic.IEnumerable`1[T] pins) (at <30c2a97e47dc4320b532fd7ef8e77b59>:0)
BetterCartographyTable.Managers.PlayerSaveManager.OnSave () (at <30c2a97e47dc4320b532fd7ef8e77b59>:0)
BetterCartographyTable.Patches.PlayerPatches+SaveSharedPinsOnPlayerSave.Prefix () (at <30c2a97e47dc4320b532fd7ef8e77b59>:0)
(wrapper dynamic-method) Player.DMD<Player::Save>(Player,ZPackage)
(wrapper dynamic-method) PlayerProfile.DMD<PlayerProfile::SavePlayerData>(PlayerProfile,Player)
(wrapper dynamic-method) Game.DMD<Game::SavePlayerProfile>(Game,bool)
(wrapper dynamic-method) Game.DMD<Game::Shutdown>(Game,bool)
(wrapper dynamic-method) Game.DMD<Game::OnApplicationQuit>(Game)

[Warning: Unity Log] 04/05/2024 15:02:48: Player destroyed sec:-5,22  pos:(-333.24, 138.21, 1389.04)  zdopos:(-333.24, 138.21, 1389.04)  ref (-333.24, 138.21, 1389.04)
[Warning: Unity Log] 04/05/2024 15:02:48: Local player destroyed

[LogOutput.log](https://github.com/nbusseneau/BetterCartographyTable/files/14889783/LogOutput.log)

**Comment by nbusseneau** [comment]
Hi!

- What do you mean by loss of mobility?
- How do the crashes happen?
- What other mods are you using?

Thank you for reporting back here but I can't really do anything with just this, I need more details on what's happening... 😅

**Comment by Atlasroar** [comment]
The log was added at the bottom of the first post

We're playing on no map with + no map/cartographer table mod

- loss of mobility
 - when using the cartographer table to view the map while using the above mod players were crashing if the table was guild only and they tried to use it
 - the opposite could be said for the person who changed it to guild only. it would instead close the map normally but they couldnt use any other keys except WASD

**Comment by nbusseneau** [comment]
Thanks for the additional details. I still don't understand what "loss of mobility" means, and as for the rest I'm not really surprised because the way "no map" works in vanilla is there's no map at all, so of course there would be incompatibility. I know you've opened #5 and I intend to look into it but until then I don't expect you can use it 😅

**Comment by nbusseneau** [comment]
Also, about

> The log was added at the bottom of the first post

Yes, indeed, thanks for that, but just in case: just giving the log without additional details does not help much, the logs do not actually log all that much about what you did to get to a crash. That's why all of details about what happens + how to reproduce the crash + the logs are important :)

**Comment by Atlasroar** [comment]
Gotcha. yeah wearing myself thin lmao. so apologies for lack of information.

Loss of mobility worked or happened like this
- no map mode
- two mods were added to allow "explorers" the ability to use the cartography table for their "guild". (guild mod)
Mods added were no map cartography table and your mod. See this [mod](https://thunderstore.io/c/valheim/p/Visteus/NoMap_Cartography_Map/)

The idea was that players who choose profession "explorer" See this [Mod](https://thunderstore.io/c/valheim/p/Smoothbrain/Exploration/) (can use the table with correct level)

Thus giving rise to explorers being more important per guild along with their benefits they provide. (double loot etc). 
What would happen is that when players placed a cartography table the table would work fine except in two circumstances

1. If the table was in "guild" mode, it would sometimes crash users who were not part of the guild.
2. If the table was/wasnt in guild mode and the user tried to exit the map menu with anything other than the ESC key to close it, they would lose function of all keys and be forced into "walk" mode. The only keys that would work would be WASD and the ESC BUT you couldnt use the mouse.

Very simply it was like being....tabbed out of the game but partially tabbed in.

**Comment by Atlasroar** [comment]
![image](https://github.com/nbusseneau/BetterCartographyTable/assets/64485452/d32045d3-5f14-48d7-b50d-35164390af7f)
This is the only....non helpful information i have. As for the loss of xp etc that's becuase of server characters and them having to force quit. So afaik nothing to do with your mod.

**Comment by nbusseneau** [comment]
Thanks for the additional details and context, this helps a lot 😄

**Comment by nbusseneau** [comment]
Are you using any other mods in your mod packs? Can you give me the full mod list? I think the crashes are due to incompatibility with another mod that also tries to do things with pins or the map.

**Comment by Atlasroar** [comment]
yep Pack is [here](https://thunderstore.io/c/valheim/p/GothicModding/Valhalla_Gothic_Pack/)

Theres a couple "pin" mods like death pin for compass, and some other mods i can think of taht would have been affecting it at the time. Though i cant say what the issue would have been considering that other than using the table, everything worked fine. Or appeared to work fine. Changelogs include all mods used and removed since the error report. So Version 4.0.0 up to likely 4.0.6 ish when it was removed.

**Comment by nbusseneau** [comment]
> Though i cant say what the issue would have been considering that other than using the table, everything worked fine.

Yeah that's not surprising, sending/receiving data is only done when interacting with the tables, and it's more likely this would be the part to fail because it's where most of the mod logic lies.

**Comment by nbusseneau** [comment]
Compatibility with other mods should be greatly improved in version [0.4.0](https://github.com/nbusseneau/BetterCartographyTable/releases/tag/0.4.0).
