### ISSUE TITLE
Error: Unity Log NullReferenceException Spammed in console

### ISSUE THREAD

**Issue by TheCavemanOfficial** [nbusseneau/BetterCartographyTable#9]
this is the error being spammed in the console. 

![image](https://github.com/nbusseneau/BetterCartographyTable/assets/5055389/8d09ec34-55ee-4548-9e71-4f3e523633de)

Here is the list of mods, i dont see what would be conflicting

![image](https://github.com/nbusseneau/BetterCartographyTable/assets/5055389/85a9369a-4991-4370-aa90-6b615e35139a)

**Comment by TheCavemanOfficial** [comment]
fixed with update i guess? its not spamming anymore

**Comment by nbusseneau** [comment]
Yes indeed, this was fixed in 0.4.2. I noticed it a bit late because this was not happening in all situations, sorry 😅
